export const STANDARD_TOUR_STEPS = [
  // ── Section 1: Header ──────────────────────────────────────────────
  {
    target: '[data-tour="header-cart-icon"]',
    title: 'Welcome to IHG Products',
    content: 'This quick tour covers all the key features of the catalog. Your cart lives here — items you add appear with a count badge.',
    placement: 'bottom-end',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="header-user-menu"]',
    title: 'User Menu',
    content: 'Access your profile, switch customer accounts, and log out securely from the user menu in the top right.',
    placement: 'bottom-end',
    skipBeacon: true,
    skipScroll: true,
  },

  // ── Section 2: Search & Toolbar ───────────────────────────────────
  {
    target: '[data-tour="search-bar"]',
    title: 'Product Search Bar',
    content: 'Type a product name, SKU, category, or spec like "3000K IP65 downlight". Results update instantly as you type.',
    placement: 'bottom',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="ai-search-button"]',
    title: 'AI-Powered Search',
    content: 'Describe what you need in plain English — "dimmable 24V LED driver 150W in stock". AI translates your words into precise catalog filters.',
    placement: 'bottom',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="results-count"]',
    title: 'Live Results Count',
    content: 'Shows the total number of matching products. Updates instantly as you type or apply filters.',
    placement: 'bottom',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="sort-control"]',
    title: 'Sort Products',
    content: 'Sort by stock level, price (low to high / high to low), discount, or inventory value. Default is highest stock first.',
    placement: 'bottom',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="density-toggle"]',
    title: 'Grid Density',
    content: 'Switch between comfortable (larger cards) and compact (more per row) layout depending on your screen.',
    placement: 'bottom',
    skipBeacon: true,
    skipScroll: true,
  },

  // ── Section 3: Product Card ────────────────────────────────────────
  {
    target: '[data-tour="product-card"]',
    title: 'Product Card',
    content: 'Each card is one product. Click anywhere on it to open the full product detail sheet with specs, images, and stock breakdown.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="product-card-brand-category"]',
    title: 'Brand & Category',
    content: 'The brand and category tags are shown at the top of the card. Click either chip in the filter panel to narrow to similar items.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="product-card-item-code"]',
    title: 'Item Code (SKU)',
    content: 'The unique product identifier. Click it to copy to clipboard instantly — useful for order entry.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="product-card-item-name"]',
    title: 'Product Name',
    content: 'The full product description. Hover to see the complete title if it is truncated.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="product-card-price"]',
    title: 'Pricing',
    content: 'The active price shown in bold. When a promotion is running, the original price appears struck-through beside it.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="product-card-stock"]',
    title: 'Stock Level',
    content: 'Color-coded availability: green = healthy, orange = low (≤5 units), red = critical (1 unit). Grey = out of stock.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="product-card-customer-signals"]',
    title: 'Customer Signals',
    content: 'Blue badge = happy customers. Green badge = units sold. High numbers indicate a proven bestseller.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="product-card"]',
    title: 'Card Hover Actions',
    content: 'Hover over a card to reveal three action buttons in the top-right corner: ❤ Save to wishlist, 👁 Quick view specs, and 🚩 Report a data issue.',
    placement: 'auto',
    skipBeacon: true,
    skipScroll: true,
    data: { forceHover: true },
  },

  // ── Section 4: Filter Panel ────────────────────────────────────────
  {
    target: '[data-tour="filter-panel"]',
    title: 'Filter Sidebar',
    content: 'Narrow results instantly. All filters stack — combine brand + in-stock + price range simultaneously.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-instock-toggle"]',
    title: 'In Stock Only',
    content: 'Toggle to hide all out-of-stock items. Ideal when you need immediate availability.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-promo-toggle"]',
    title: 'Promotions Filter',
    content: 'Show only items currently on promotion. Combine with In Stock to find discounted, available products.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-price-range"]',
    title: 'Price Range',
    content: 'Set a minimum and maximum AED price. Prices reflect the active promo rate when applicable.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-brand-facet"]',
    title: 'Brand Filter',
    content: 'Select one or more brands. The count shows how many products match. Brands with zero results are hidden.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-category-facet"]',
    title: 'Category Filter',
    content: 'Narrow to a product category like "Downlights" or "LED Strips". Works the same as brand selection.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-power-slider"]',
    title: 'Power (Wattage) Filter',
    content: 'Drag handles to filter by wattage range. Useful for specification-driven procurement.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-color-temp-slider"]',
    title: 'Color Temperature',
    content: 'Filter by Kelvin (e.g. 3000K warm white to 6500K daylight). Only appears when CCT data is available.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },
  {
    target: '[data-tour="filter-panel-clear-all"]',
    title: 'Reset All Filters',
    content: 'Clears every active filter at once and returns to the full unfiltered catalog.',
    placement: 'right',
    skipBeacon: true,
    skipScroll: true,
  },

  // ── Section 5: Product Detail ──────────────────────────────────────
  {
    target: 'body',
    title: 'Opening Product Detail…',
    content: 'Next up — the full product detail sheet. We\'ll open it for you so you can see every section a salesperson uses when quoting a customer.',
    placement: 'center',
    skipBeacon: true,
    data: { triggerAction: 'openProductDetail', waitForSelector: '[data-tour="product-detail-panel"]' },
  },
  {
    target: '[data-tour="product-detail-panel"]',
    title: 'Product Detail Sheet',
    content: 'A full-width sheet that slides in from the right with images, full specs, stock, pricing, business signals, and related products. Use the × button (top right) or "Back to results" (top left) to close.',
    placement: 'left',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-images"]',
    title: 'Image Gallery',
    content: 'Main product image with a thumbnail strip below — click any thumbnail to switch. A green "SAVE %" badge appears in the corner when the product is on promotion. The gallery stays sticky as you scroll the rest of the sheet.',
    placement: 'right',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-info"]',
    title: 'Product Information',
    content: 'Brand · Category at the top, then the SKU (item code), full product name, and a short description. Everything you need to identify the right SKU before quoting.',
    placement: 'left',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-price"]',
    title: 'Pricing',
    content: 'Active selling price in AED. If a promotion is running, the original price appears struck-through with a green "SAVE X%" badge. "Price on request" means pricing is not configured yet — check with admin before quoting.',
    placement: 'left',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-stock-detail"]',
    title: 'Stock Status',
    content: 'A live indicator: green dot + "IN STOCK · N Nos" means available now with the exact quantity. A red dot + "OUT OF STOCK" means none on hand. For a per-warehouse breakdown, see the Stock Details tab further down.',
    placement: 'top',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-business-signals"]',
    title: 'Business Signals',
    content: 'Quick social-proof: Star Rating from previous orders, Happy Customers count, and total Quantity Sold. Use these when recommending — high numbers indicate a proven, trusted product.',
    placement: 'top',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-add-to-cart"]',
    title: 'Add to Cart',
    content: 'Add this product to the active sales cart. In Sales Mode you\'ll get a quantity stepper here once it\'s in the cart, so you can adjust without reopening anything.',
    placement: 'top',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-tabs"]',
    title: 'Product Tabs',
    content: 'Three tabs: "Product Details" (full technical specs — power, lumens, color temp, IP rating, dimensions, etc.), "Stock Details" (per-warehouse quantity breakdown), and "QR Code" (scannable code for the SKU).',
    placement: 'top',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-related"]',
    title: 'Related Products',
    content: 'Suggestions that help you upsell or complete an order: "Bought Together" (frequently paired SKUs), "Add Ons" (accessories), and "Must Use" (essential companions like drivers for LEDs). Scroll the row to browse and click any card to open its detail sheet.',
    placement: 'top',
    skipBeacon: true,
  },
  {
    target: '[data-tour="product-detail-close"]',
    title: 'Close Detail Sheet',
    content: 'Click × to close the panel and return to the catalog. Your filters, sort order, and scroll position are preserved so you don\'t lose your place.',
    placement: 'left',
    skipBeacon: true,
  },

  // ── Section 6: Sales Mode (filtered out for non-sales users) ───────
  {
    target: '[data-tour="product-card-add-to-cart"]',
    title: 'Add to Cart (Sales Mode)',
    content: 'In Sales Mode each card shows a direct "Add to Cart" button. Click to set quantity and confirm.',
    placement: 'bottom',
    skipBeacon: true,
    data: { salesModeOnly: true },
  },
  {
    target: '[data-tour="product-card-qty-stepper"]',
    title: 'Quantity Stepper',
    content: 'After adding to cart the stepper appears. Use − and + to adjust without reopening any modal.',
    placement: 'bottom',
    skipBeacon: true,
    data: { salesModeOnly: true },
  },
  {
    target: '[data-tour="sales-atc-modal"]',
    title: 'Confirm Your Order',
    content: 'Review product details, enter quantity, and confirm. The total price updates live.',
    placement: 'left',
    skipBeacon: true,
    data: { salesModeOnly: true },
  },
  {
    target: '[data-tour="cart-modal"]',
    title: 'Sales Cart',
    content: 'Your cart accumulates items here. Review quantities, see line totals, and proceed to quotation or checkout.',
    placement: 'auto',
    skipBeacon: true,
    data: { salesModeOnly: true },
  },

  // ── Final step ────────────────────────────────────────────────────
  {
    target: 'body',
    title: 'Tour Complete!',
    content: 'You\'ve seen all the key features of the IHG Product Catalog. Click the ? button in the header anytime to restart this tour.',
    placement: 'center',
    skipBeacon: true,
    data: { isFinalStep: true },
  },
];

export const SALES_TOUR_STEPS = STANDARD_TOUR_STEPS;
