export const PAGE_SIZE_OPTIONS = [20, 50, 100];

export const VISIBLE_FILTERS = [
  { key: "brand", label: "Brand" },
  { key: "item_group", label: "Item Group" },
  { key: "category_list", label: "Category" },
  { key: "series", label: "Series" },
  { key: "product_type", label: "Product Type" },
  { key: "power", label: "Power" },
  { key: "color_temp", label: "Color Temperature" },
  { key: "ip_rate", label: "IP Rating" },
  { key: "lumen_output", label: "Lumen Output" },
  { key: "mounting", label: "Mounting" },
  { key: "beam_angle", label: "Beam Angle" },
  { key: "lamp_type", label: "Lamp Type" },
  { key: "body_finish", label: "Body Finish" },
  { key: "material", label: "Material" },
  { key: "input_voltage", label: "Input" },
  { key: "output_current", label: "Output Current" },
  { key: "output_voltage", label: "Output Voltage" },
  { key: "warranty", label: "Warranty" },
  { key: "is_manufactured_item", label: "Manufactured Item" },
];

export const FILTER_LABEL_MAP = {
  brand: "Brand",
  category_list: "Category",
  item_group: "Item Group",
  series: "Series",
  product_type: "Product Type",
  power: "Power",
  color_temp: "Color Temperature",
  ip_rate: "IP Rating",
  lumen_output: "Lumen Output",
  beam_angle: "Beam Angle",
  mounting: "Mounting",
  body_finish: "Body Finish",
  lamp_type: "Lamp Type",
  material: "Material",
  input_voltage: "Input",
  output_voltage: "Output Voltage",
  output_current: "Output Current",
  warranty: "Warranty",
  is_manufactured_item: "Manufactured Item",
  variant_of: "Variant Of",
  in_stock: "In Stock",
  show_promotion: "Promo",
  rate_range: "Rate",
  offer_rate_range: "Offer Rate",
  stock_range: "Stock",
  discount_percentage_range: "Discount Percentage",
  power_value_range: "Power",
  color_temp_kelvin_range: "Color Temp Kelvin",
  ip_rating_numeric_range: "IP Rating Numeric",
  product_star_rating_range: "Star Rating",
  customer_count_range: "Happy Customers",
};
